{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "https://velog.io/@heyoni/python-asyncio-1"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 객체\n",
    "asyncio는 4가지 중요한 객체를 가지고 있다. 그 객체들은 다음과 같다.\n",
    "1. coroutine\n",
    "\n",
    "2. future\n",
    "\n",
    "3. task\n",
    "\n",
    "4. event_loop"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### coroutine 구조"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#cpython/Lib/_collections_abc.py\n",
    "from abc import ABCMeta, abstractmethod\n",
    "\n",
    "GenericAlias = type(list[int])\n",
    "def _check_methods(C, *methods):\n",
    "    mro = C.__mro__\n",
    "    for method in methods:\n",
    "        for B in mro:\n",
    "            if method in B.__dict__:\n",
    "                if B.__dict__[method] is None:\n",
    "                    return NotImplemented\n",
    "                break\n",
    "        else:\n",
    "            return NotImplemented\n",
    "    return True\n",
    "\n",
    "class Awaitable(metaclass=ABCMeta):\n",
    "\n",
    "    __slots__ = ()\n",
    "\n",
    "    @abstractmethod\n",
    "    def __await__(self):\n",
    "        yield\n",
    "\n",
    "    @classmethod\n",
    "    def __subclasshook__(cls, C):\n",
    "        if cls is Awaitable:\n",
    "            return _check_methods(C, \"__await__\")\n",
    "        return NotImplemented\n",
    "\n",
    "    __class_getitem__ = classmethod(GenericAlias)\n",
    "\n",
    "\n",
    "class Coroutine(Awaitable):\n",
    "\n",
    "    __slots__ = ()\n",
    "\n",
    "    @abstractmethod\n",
    "    def send(self, value):\n",
    "        \"\"\"Send a value into the coroutine.\n",
    "        Return next yielded value or raise StopIteration.\n",
    "        \"\"\"\n",
    "        raise StopIteration\n",
    "\n",
    "    @abstractmethod\n",
    "    def throw(self, typ, val=None, tb=None):\n",
    "        \"\"\"Raise an exception in the coroutine.\n",
    "        Return next yielded value or raise StopIteration.\n",
    "        \"\"\"\n",
    "        if val is None:\n",
    "            if tb is None:\n",
    "                raise typ\n",
    "            val = typ()\n",
    "        if tb is not None:\n",
    "            val = val.with_traceback(tb)\n",
    "        raise val\n",
    "\n",
    "    def close(self):\n",
    "        \"\"\"Raise GeneratorExit inside coroutine.\n",
    "        \"\"\"\n",
    "        try:\n",
    "            self.throw(GeneratorExit)\n",
    "        except (GeneratorExit, StopIteration):\n",
    "            pass\n",
    "        else:\n",
    "            raise RuntimeError(\"coroutine ignored GeneratorExit\")\n",
    "\n",
    "    @classmethod\n",
    "    def __subclasshook__(cls, C):\n",
    "        if cls is Coroutine:\n",
    "            return _check_methods(C, '__await__', 'send', 'throw', 'close')\n",
    "        return NotImplemented"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### future 구조"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import events\n",
    "import base_futures\n",
    "import format_helpers\n",
    "import exceptions\n",
    "import contextvars\n",
    "_PENDING = base_futures._PENDING\n",
    "_CANCELLED = base_futures._CANCELLED\n",
    "_FINISHED = base_futures._FINISHED\n",
    "\n",
    "class Future:\n",
    "    \"\"\"This class is *almost* compatible with concurrent.futures.Future.\n",
    "\n",
    "    Differences:\n",
    "\n",
    "    - This class is not thread-safe.\n",
    "\n",
    "    - result() and exception() do not take a timeout argument and\n",
    "      raise an exception when the future isn't done yet.\n",
    "\n",
    "    - Callbacks registered with add_done_callback() are always called\n",
    "      via the event loop's call_soon().\n",
    "\n",
    "    - This class is not compatible with the wait() and as_completed()\n",
    "      methods in the concurrent.futures package.\n",
    "\n",
    "    (In Python 3.4 or later we may be able to unify the implementations.)\n",
    "    \"\"\"\n",
    "\n",
    "    # Class variables serving as defaults for instance variables.\n",
    "    _state = _PENDING\n",
    "    _result = None\n",
    "    _exception = None\n",
    "    _loop = None\n",
    "    _source_traceback = None\n",
    "    _cancel_message = None\n",
    "    # A saved CancelledError for later chaining as an exception context.\n",
    "    _cancelled_exc = None\n",
    "\n",
    "    # This field is used for a dual purpose:\n",
    "    # - Its presence is a marker to declare that a class implements\n",
    "    #   the Future protocol (i.e. is intended to be duck-type compatible).\n",
    "    #   The value must also be not-None, to enable a subclass to declare\n",
    "    #   that it is not compatible by setting this to None.\n",
    "    # - It is set by __iter__() below so that Task._step() can tell\n",
    "    #   the difference between\n",
    "    #   `await Future()` or`yield from Future()` (correct) vs.\n",
    "    #   `yield Future()` (incorrect).\n",
    "    _asyncio_future_blocking = False\n",
    "\n",
    "    __log_traceback = False\n",
    "\n",
    "    def __init__(self, *, loop=None):\n",
    "        \"\"\"Initialize the future.\n",
    "\n",
    "        The optional event_loop argument allows explicitly setting the event\n",
    "        loop object used by the future. If it's not provided, the future uses\n",
    "        the default event loop.\n",
    "        \"\"\"\n",
    "        if loop is None:\n",
    "            self._loop = events.get_event_loop()\n",
    "        else:\n",
    "            self._loop = loop\n",
    "        self._callbacks = []\n",
    "        if self._loop.get_debug():\n",
    "            self._source_traceback = format_helpers.extract_stack(\n",
    "                sys._getframe(1))\n",
    "\n",
    "    def __repr__(self):\n",
    "        return base_futures._future_repr(self)\n",
    "\n",
    "    def __del__(self):\n",
    "        if not self.__log_traceback:\n",
    "            # set_exception() was not called, or result() or exception()\n",
    "            # has consumed the exception\n",
    "            return\n",
    "        exc = self._exception\n",
    "        context = {\n",
    "            'message':\n",
    "                f'{self.__class__.__name__} exception was never retrieved',\n",
    "            'exception': exc,\n",
    "            'future': self,\n",
    "        }\n",
    "        if self._source_traceback:\n",
    "            context['source_traceback'] = self._source_traceback\n",
    "        self._loop.call_exception_handler(context)\n",
    "\n",
    "    __class_getitem__ = classmethod(GenericAlias)\n",
    "\n",
    "    @property\n",
    "    def _log_traceback(self):\n",
    "        return self.__log_traceback\n",
    "\n",
    "    @_log_traceback.setter\n",
    "    def _log_traceback(self, val):\n",
    "        if val:\n",
    "            raise ValueError('_log_traceback can only be set to False')\n",
    "        self.__log_traceback = False\n",
    "\n",
    "    def get_loop(self):\n",
    "        \"\"\"Return the event loop the Future is bound to.\"\"\"\n",
    "        loop = self._loop\n",
    "        if loop is None:\n",
    "            raise RuntimeError(\"Future object is not initialized.\")\n",
    "        return loop\n",
    "\n",
    "    def _make_cancelled_error(self):\n",
    "        \"\"\"Create the CancelledError to raise if the Future is cancelled.\n",
    "\n",
    "        This should only be called once when handling a cancellation since\n",
    "        it erases the saved context exception value.\n",
    "        \"\"\"\n",
    "        if self._cancelled_exc is not None:\n",
    "            exc = self._cancelled_exc\n",
    "            self._cancelled_exc = None\n",
    "            return exc\n",
    "\n",
    "        if self._cancel_message is None:\n",
    "            exc = exceptions.CancelledError()\n",
    "        else:\n",
    "            exc = exceptions.CancelledError(self._cancel_message)\n",
    "        return exc\n",
    "\n",
    "    def cancel(self, msg=None):\n",
    "        \"\"\"Cancel the future and schedule callbacks.\n",
    "\n",
    "        If the future is already done or cancelled, return False.  Otherwise,\n",
    "        change the future's state to cancelled, schedule the callbacks and\n",
    "        return True.\n",
    "        \"\"\"\n",
    "        self.__log_traceback = False\n",
    "        if self._state != _PENDING:\n",
    "            return False\n",
    "        self._state = _CANCELLED\n",
    "        self._cancel_message = msg\n",
    "        self.__schedule_callbacks()\n",
    "        return True\n",
    "\n",
    "    def __schedule_callbacks(self):\n",
    "        \"\"\"Internal: Ask the event loop to call all callbacks.\n",
    "\n",
    "        The callbacks are scheduled to be called as soon as possible. Also\n",
    "        clears the callback list.\n",
    "        \"\"\"\n",
    "        callbacks = self._callbacks[:]\n",
    "        if not callbacks:\n",
    "            return\n",
    "\n",
    "        self._callbacks[:] = []\n",
    "        for callback, ctx in callbacks:\n",
    "            self._loop.call_soon(callback, self, context=ctx)\n",
    "\n",
    "    def cancelled(self):\n",
    "        \"\"\"Return True if the future was cancelled.\"\"\"\n",
    "        return self._state == _CANCELLED\n",
    "\n",
    "    # Don't implement running(); see http://bugs.python.org/issue18699\n",
    "\n",
    "    def done(self):\n",
    "        \"\"\"Return True if the future is done.\n",
    "\n",
    "        Done means either that a result / exception are available, or that the\n",
    "        future was cancelled.\n",
    "        \"\"\"\n",
    "        return self._state != _PENDING\n",
    "\n",
    "    def result(self):\n",
    "        \"\"\"Return the result this future represents.\n",
    "\n",
    "        If the future has been cancelled, raises CancelledError.  If the\n",
    "        future's result isn't yet available, raises InvalidStateError.  If\n",
    "        the future is done and has an exception set, this exception is raised.\n",
    "        \"\"\"\n",
    "        if self._state == _CANCELLED:\n",
    "            exc = self._make_cancelled_error()\n",
    "            raise exc\n",
    "        if self._state != _FINISHED:\n",
    "            raise exceptions.InvalidStateError('Result is not ready.')\n",
    "        self.__log_traceback = False\n",
    "        if self._exception is not None:\n",
    "            raise self._exception.with_traceback(self._exception_tb)\n",
    "        return self._result\n",
    "\n",
    "    def exception(self):\n",
    "        \"\"\"Return the exception that was set on this future.\n",
    "\n",
    "        The exception (or None if no exception was set) is returned only if\n",
    "        the future is done.  If the future has been cancelled, raises\n",
    "        CancelledError.  If the future isn't done yet, raises\n",
    "        InvalidStateError.\n",
    "        \"\"\"\n",
    "        if self._state == _CANCELLED:\n",
    "            exc = self._make_cancelled_error()\n",
    "            raise exc\n",
    "        if self._state != _FINISHED:\n",
    "            raise exceptions.InvalidStateError('Exception is not set.')\n",
    "        self.__log_traceback = False\n",
    "        return self._exception\n",
    "\n",
    "    def add_done_callback(self, fn, *, context=None):\n",
    "        \"\"\"Add a callback to be run when the future becomes done.\n",
    "\n",
    "        The callback is called with a single argument - the future object. If\n",
    "        the future is already done when this is called, the callback is\n",
    "        scheduled with call_soon.\n",
    "        \"\"\"\n",
    "        if self._state != _PENDING:\n",
    "            self._loop.call_soon(fn, self, context=context)\n",
    "        else:\n",
    "            if context is None:\n",
    "                context = contextvars.copy_context()\n",
    "            self._callbacks.append((fn, context))\n",
    "\n",
    "    # New method not in PEP 3148.\n",
    "\n",
    "    def remove_done_callback(self, fn):\n",
    "        \"\"\"Remove all instances of a callback from the \"call when done\" list.\n",
    "\n",
    "        Returns the number of callbacks removed.\n",
    "        \"\"\"\n",
    "        filtered_callbacks = [(f, ctx)\n",
    "                              for (f, ctx) in self._callbacks\n",
    "                              if f != fn]\n",
    "        removed_count = len(self._callbacks) - len(filtered_callbacks)\n",
    "        if removed_count:\n",
    "            self._callbacks[:] = filtered_callbacks\n",
    "        return removed_count\n",
    "\n",
    "    # So-called internal methods (note: no set_running_or_notify_cancel()).\n",
    "\n",
    "    def set_result(self, result):\n",
    "        \"\"\"Mark the future done and set its result.\n",
    "\n",
    "        If the future is already done when this method is called, raises\n",
    "        InvalidStateError.\n",
    "        \"\"\"\n",
    "        if self._state != _PENDING:\n",
    "            raise exceptions.InvalidStateError(f'{self._state}: {self!r}')\n",
    "        self._result = result\n",
    "        self._state = _FINISHED\n",
    "        self.__schedule_callbacks()\n",
    "\n",
    "    def set_exception(self, exception):\n",
    "        \"\"\"Mark the future done and set an exception.\n",
    "\n",
    "        If the future is already done when this method is called, raises\n",
    "        InvalidStateError.\n",
    "        \"\"\"\n",
    "        if self._state != _PENDING:\n",
    "            raise exceptions.InvalidStateError(f'{self._state}: {self!r}')\n",
    "        if isinstance(exception, type):\n",
    "            exception = exception()\n",
    "        if isinstance(exception, StopIteration):\n",
    "            new_exc = RuntimeError(\"StopIteration interacts badly with \"\n",
    "                                   \"generators and cannot be raised into a \"\n",
    "                                   \"Future\")\n",
    "            new_exc.__cause__ = exception\n",
    "            new_exc.__context__ = exception\n",
    "            exception = new_exc\n",
    "        self._exception = exception\n",
    "        self._exception_tb = exception.__traceback__\n",
    "        self._state = _FINISHED\n",
    "        self.__schedule_callbacks()\n",
    "        self.__log_traceback = True\n",
    "\n",
    "    def __await__(self):\n",
    "        if not self.done():\n",
    "            self._asyncio_future_blocking = True\n",
    "            yield self  # This tells Task to wait for completion.\n",
    "        if not self.done():\n",
    "            raise RuntimeError(\"await wasn't used with future\")\n",
    "        return self.result()  # May raise too.\n",
    "\n",
    "    __iter__ = __await__  # make compatible with 'yield from'.\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### task 구조"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import futures\n",
    "import coroutines\n",
    "from tasks import *\n",
    "class Task(futures._PyFuture):  # Inherit Python Task implementation\n",
    "                                # from a Python Future implementation.\n",
    "\n",
    "    \"\"\"A coroutine wrapped in a Future.\"\"\"\n",
    "\n",
    "    # An important invariant maintained while a Task not done:\n",
    "    # _fut_waiter is either None or a Future.  The Future\n",
    "    # can be either done() or not done().\n",
    "    # The task can be in any of 3 states:\n",
    "    #\n",
    "    # - 1: _fut_waiter is not None and not _fut_waiter.done():\n",
    "    #      __step() is *not* scheduled and the Task is waiting for _fut_waiter.\n",
    "    # - 2: (_fut_waiter is None or _fut_waiter.done()) and __step() is scheduled:\n",
    "    #       the Task is waiting for __step() to be executed.\n",
    "    # - 3:  _fut_waiter is None and __step() is *not* scheduled:\n",
    "    #       the Task is currently executing (in __step()).\n",
    "    #\n",
    "    # * In state 1, one of the callbacks of __fut_waiter must be __wakeup().\n",
    "    # * The transition from 1 to 2 happens when _fut_waiter becomes done(),\n",
    "    #   as it schedules __wakeup() to be called (which calls __step() so\n",
    "    #   we way that __step() is scheduled).\n",
    "    # * It transitions from 2 to 3 when __step() is executed, and it clears\n",
    "    #   _fut_waiter to None.\n",
    "\n",
    "    # If False, don't log a message if the task is destroyed while its\n",
    "    # status is still pending\n",
    "    _log_destroy_pending = True\n",
    "\n",
    "    def __init__(self, coro, *, loop=None, name=None, context=None,\n",
    "                 eager_start=False):\n",
    "        super().__init__(loop=loop)\n",
    "        if self._source_traceback:\n",
    "            del self._source_traceback[-1]\n",
    "        if not coroutines.iscoroutine(coro):\n",
    "            # raise after Future.__init__(), attrs are required for __del__\n",
    "            # prevent logging for pending task in __del__\n",
    "            self._log_destroy_pending = False\n",
    "            raise TypeError(f\"a coroutine was expected, got {coro!r}\")\n",
    "\n",
    "        if name is None:\n",
    "            self._name = f'Task-{_task_name_counter()}'\n",
    "        else:\n",
    "            self._name = str(name)\n",
    "\n",
    "        self._num_cancels_requested = 0\n",
    "        self._must_cancel = False\n",
    "        self._fut_waiter = None\n",
    "        self._coro = coro\n",
    "        if context is None:\n",
    "            self._context = contextvars.copy_context()\n",
    "        else:\n",
    "            self._context = context\n",
    "\n",
    "        if eager_start and self._loop.is_running():\n",
    "            self.__eager_start()\n",
    "        else:\n",
    "            self._loop.call_soon(self.__step, context=self._context)\n",
    "            _register_task(self)\n",
    "\n",
    "    def __del__(self):\n",
    "        if self._state == futures._PENDING and self._log_destroy_pending:\n",
    "            context = {\n",
    "                'task': self,\n",
    "                'message': 'Task was destroyed but it is pending!',\n",
    "            }\n",
    "            if self._source_traceback:\n",
    "                context['source_traceback'] = self._source_traceback\n",
    "            self._loop.call_exception_handler(context)\n",
    "        super().__del__()\n",
    "\n",
    "    __class_getitem__ = classmethod(GenericAlias)\n",
    "\n",
    "    def __repr__(self):\n",
    "        return base_tasks._task_repr(self)\n",
    "\n",
    "    def get_coro(self):\n",
    "        return self._coro\n",
    "\n",
    "    def get_context(self):\n",
    "        return self._context\n",
    "\n",
    "    def get_name(self):\n",
    "        return self._name\n",
    "\n",
    "    def set_name(self, value):\n",
    "        self._name = str(value)\n",
    "\n",
    "    def set_result(self, result):\n",
    "        raise RuntimeError('Task does not support set_result operation')\n",
    "\n",
    "    def set_exception(self, exception):\n",
    "        raise RuntimeError('Task does not support set_exception operation')\n",
    "\n",
    "    def get_stack(self, *, limit=None):\n",
    "        \"\"\"Return the list of stack frames for this task's coroutine.\n",
    "\n",
    "        If the coroutine is not done, this returns the stack where it is\n",
    "        suspended.  If the coroutine has completed successfully or was\n",
    "        cancelled, this returns an empty list.  If the coroutine was\n",
    "        terminated by an exception, this returns the list of traceback\n",
    "        frames.\n",
    "\n",
    "        The frames are always ordered from oldest to newest.\n",
    "\n",
    "        The optional limit gives the maximum number of frames to\n",
    "        return; by default all available frames are returned.  Its\n",
    "        meaning differs depending on whether a stack or a traceback is\n",
    "        returned: the newest frames of a stack are returned, but the\n",
    "        oldest frames of a traceback are returned.  (This matches the\n",
    "        behavior of the traceback module.)\n",
    "\n",
    "        For reasons beyond our control, only one stack frame is\n",
    "        returned for a suspended coroutine.\n",
    "        \"\"\"\n",
    "        return base_tasks._task_get_stack(self, limit)\n",
    "\n",
    "    def print_stack(self, *, limit=None, file=None):\n",
    "        \"\"\"Print the stack or traceback for this task's coroutine.\n",
    "\n",
    "        This produces output similar to that of the traceback module,\n",
    "        for the frames retrieved by get_stack().  The limit argument\n",
    "        is passed to get_stack().  The file argument is an I/O stream\n",
    "        to which the output is written; by default output is written\n",
    "        to sys.stderr.\n",
    "        \"\"\"\n",
    "        return base_tasks._task_print_stack(self, limit, file)\n",
    "\n",
    "    def cancel(self, msg=None):\n",
    "        \"\"\"Request that this task cancel itself.\n",
    "\n",
    "        This arranges for a CancelledError to be thrown into the\n",
    "        wrapped coroutine on the next cycle through the event loop.\n",
    "        The coroutine then has a chance to clean up or even deny\n",
    "        the request using try/except/finally.\n",
    "\n",
    "        Unlike Future.cancel, this does not guarantee that the\n",
    "        task will be cancelled: the exception might be caught and\n",
    "        acted upon, delaying cancellation of the task or preventing\n",
    "        cancellation completely.  The task may also return a value or\n",
    "        raise a different exception.\n",
    "\n",
    "        Immediately after this method is called, Task.cancelled() will\n",
    "        not return True (unless the task was already cancelled).  A\n",
    "        task will be marked as cancelled when the wrapped coroutine\n",
    "        terminates with a CancelledError exception (even if cancel()\n",
    "        was not called).\n",
    "\n",
    "        This also increases the task's count of cancellation requests.\n",
    "        \"\"\"\n",
    "        self._log_traceback = False\n",
    "        if self.done():\n",
    "            return False\n",
    "        self._num_cancels_requested += 1\n",
    "        # These two lines are controversial.  See discussion starting at\n",
    "        # https://github.com/python/cpython/pull/31394#issuecomment-1053545331\n",
    "        # Also remember that this is duplicated in _asynciomodule.c.\n",
    "        # if self._num_cancels_requested > 1:\n",
    "        #     return False\n",
    "        if self._fut_waiter is not None:\n",
    "            if self._fut_waiter.cancel(msg=msg):\n",
    "                # Leave self._fut_waiter; it may be a Task that\n",
    "                # catches and ignores the cancellation so we may have\n",
    "                # to cancel it again later.\n",
    "                return True\n",
    "        # It must be the case that self.__step is already scheduled.\n",
    "        self._must_cancel = True\n",
    "        self._cancel_message = msg\n",
    "        return True\n",
    "\n",
    "    def cancelling(self):\n",
    "        \"\"\"Return the count of the task's cancellation requests.\n",
    "\n",
    "        This count is incremented when .cancel() is called\n",
    "        and may be decremented using .uncancel().\n",
    "        \"\"\"\n",
    "        return self._num_cancels_requested\n",
    "\n",
    "    def uncancel(self):\n",
    "        \"\"\"Decrement the task's count of cancellation requests.\n",
    "\n",
    "        This should be called by the party that called `cancel()` on the task\n",
    "        beforehand.\n",
    "\n",
    "        Returns the remaining number of cancellation requests.\n",
    "        \"\"\"\n",
    "        if self._num_cancels_requested > 0:\n",
    "            self._num_cancels_requested -= 1\n",
    "        return self._num_cancels_requested\n",
    "\n",
    "    def __eager_start(self):\n",
    "        prev_task = _swap_current_task(self._loop, self)\n",
    "        try:\n",
    "            _register_eager_task(self)\n",
    "            try:\n",
    "                self._context.run(self.__step_run_and_handle_result, None)\n",
    "            finally:\n",
    "                _unregister_eager_task(self)\n",
    "        finally:\n",
    "            try:\n",
    "                curtask = _swap_current_task(self._loop, prev_task)\n",
    "                assert curtask is self\n",
    "            finally:\n",
    "                if self.done():\n",
    "                    self._coro = None\n",
    "                    self = None  # Needed to break cycles when an exception occurs.\n",
    "                else:\n",
    "                    _register_task(self)\n",
    "\n",
    "    def __step(self, exc=None):\n",
    "        if self.done():\n",
    "            raise exceptions.InvalidStateError(\n",
    "                f'_step(): already done: {self!r}, {exc!r}')\n",
    "        if self._must_cancel:\n",
    "            if not isinstance(exc, exceptions.CancelledError):\n",
    "                exc = self._make_cancelled_error()\n",
    "            self._must_cancel = False\n",
    "        self._fut_waiter = None\n",
    "\n",
    "        _enter_task(self._loop, self)\n",
    "        try:\n",
    "            self.__step_run_and_handle_result(exc)\n",
    "        finally:\n",
    "            _leave_task(self._loop, self)\n",
    "            self = None  # Needed to break cycles when an exception occurs.\n",
    "\n",
    "    def __step_run_and_handle_result(self, exc):\n",
    "        coro = self._coro\n",
    "        try:\n",
    "            if exc is None:\n",
    "                # We use the `send` method directly, because coroutines\n",
    "                # don't have `__iter__` and `__next__` methods.\n",
    "                result = coro.send(None)\n",
    "            else:\n",
    "                result = coro.throw(exc)\n",
    "        except StopIteration as exc:\n",
    "            if self._must_cancel:\n",
    "                # Task is cancelled right before coro stops.\n",
    "                self._must_cancel = False\n",
    "                super().cancel(msg=self._cancel_message)\n",
    "            else:\n",
    "                super().set_result(exc.value)\n",
    "        except exceptions.CancelledError as exc:\n",
    "            # Save the original exception so we can chain it later.\n",
    "            self._cancelled_exc = exc\n",
    "            super().cancel()  # I.e., Future.cancel(self).\n",
    "        except (KeyboardInterrupt, SystemExit) as exc:\n",
    "            super().set_exception(exc)\n",
    "            raise\n",
    "        except BaseException as exc:\n",
    "            super().set_exception(exc)\n",
    "        else:\n",
    "            blocking = getattr(result, '_asyncio_future_blocking', None)\n",
    "            if blocking is not None:\n",
    "                # Yielded Future must come from Future.__iter__().\n",
    "                if futures._get_loop(result) is not self._loop:\n",
    "                    new_exc = RuntimeError(\n",
    "                        f'Task {self!r} got Future '\n",
    "                        f'{result!r} attached to a different loop')\n",
    "                    self._loop.call_soon(\n",
    "                        self.__step, new_exc, context=self._context)\n",
    "                elif blocking:\n",
    "                    if result is self:\n",
    "                        new_exc = RuntimeError(\n",
    "                            f'Task cannot await on itself: {self!r}')\n",
    "                        self._loop.call_soon(\n",
    "                            self.__step, new_exc, context=self._context)\n",
    "                    else:\n",
    "                        result._asyncio_future_blocking = False\n",
    "                        result.add_done_callback(\n",
    "                            self.__wakeup, context=self._context)\n",
    "                        self._fut_waiter = result\n",
    "                        if self._must_cancel:\n",
    "                            if self._fut_waiter.cancel(\n",
    "                                    msg=self._cancel_message):\n",
    "                                self._must_cancel = False\n",
    "                else:\n",
    "                    new_exc = RuntimeError(\n",
    "                        f'yield was used instead of yield from '\n",
    "                        f'in task {self!r} with {result!r}')\n",
    "                    self._loop.call_soon(\n",
    "                        self.__step, new_exc, context=self._context)\n",
    "\n",
    "            elif result is None:\n",
    "                # Bare yield relinquishes control for one event loop iteration.\n",
    "                self._loop.call_soon(self.__step, context=self._context)\n",
    "            elif inspect.isgenerator(result):\n",
    "                # Yielding a generator is just wrong.\n",
    "                new_exc = RuntimeError(\n",
    "                    f'yield was used instead of yield from for '\n",
    "                    f'generator in task {self!r} with {result!r}')\n",
    "                self._loop.call_soon(\n",
    "                    self.__step, new_exc, context=self._context)\n",
    "            else:\n",
    "                # Yielding something else is an error.\n",
    "                new_exc = RuntimeError(f'Task got bad yield: {result!r}')\n",
    "                self._loop.call_soon(\n",
    "                    self.__step, new_exc, context=self._context)\n",
    "        finally:\n",
    "            self = None  # Needed to break cycles when an exception occurs.\n",
    "\n",
    "    def __wakeup(self, future):\n",
    "        try:\n",
    "            future.result()\n",
    "        except BaseException as exc:\n",
    "            # This may also be a cancellation.\n",
    "            self.__step(exc)\n",
    "        else:\n",
    "            # Don't pass the value of `future.result()` explicitly,\n",
    "            # as `Future.__iter__` and `Future.__await__` don't need it.\n",
    "            # If we call `_step(value, None)` instead of `_step()`,\n",
    "            # Python eval loop would use `.send(value)` method call,\n",
    "            # instead of `__next__()`, which is slower for futures\n",
    "            # that return non-generator iterators from their `__iter__`.\n",
    "            self.__step()\n",
    "        self = None  # Needed to break cycles when an exception occurs."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Events 구조\n",
    "\n",
    "\n",
    "Events의 구조는 2000줄이 넘는 관계로 말로 대체한다.   \n",
    "\n",
    "좀 특이한게 events를 상속받아서 base_events의 BaseEventLoop가 이벤트루프 객체가 된다.   \n",
    "\n",
    "BaseEventLoop객체는 이벤트 루프를 말하며 __init__에서 self만 인자로 받는다.\n",
    "\n",
    "주요 메서드로는 create_task, create_future, run_forever, stop, close, run_in_executor 등이 있다.\n",
    "\n",
    "실행 관련 메서드는 _run_once라고 추정중\n",
    "\n",
    "run_once는 이벤트 루프를 전체적으로 한번 실행해주는 함수이다.\n",
    "\n",
    "이 함수 안에서 deque에 등록된 스케줄을 순서대로 실행한다음 삭제하는 식으로 루프를 돌려준다."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
